services:
  localstack:
    image: localstack/localstack:3.8.1
    container_name: oms-localstack

    ports:
      - "4566:4566"

    environment:
      SERVICES: s3,sqs,sns,dynamodb,secretsmanager,ssm,iam,sts
      DEBUG: "1"
      AWS_DEFAULT_REGION: us-east-1
      PERSISTENCE: 1

    volumes:
      - ./init:/etc/localstack/init/ready.d
      - /var/run/docker.sock:/var/run/docker.sock

volumes:
  localstack-data: